// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: machinedb.proto

package machinedbpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MachineList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machines      []*Machine             `protobuf:"bytes,1,rep,name=machines,proto3" json:"machines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineList) Reset() {
	*x = MachineList{}
	mi := &file_machinedb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineList) ProtoMessage() {}

func (x *MachineList) ProtoReflect() protoreflect.Message {
	mi := &file_machinedb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineList.ProtoReflect.Descriptor instead.
func (*MachineList) Descriptor() ([]byte, []int) {
	return file_machinedb_proto_rawDescGZIP(), []int{0}
}

func (x *MachineList) GetMachines() []*Machine {
	if x != nil {
		return x.Machines
	}
	return nil
}

type Machine struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	EndorsementPublicKeyPkix []byte                 `protobuf:"bytes,1,opt,name=endorsement_public_key_pkix,json=endorsementPublicKeyPkix,proto3" json:"endorsement_public_key_pkix,omitempty"`
	NodeName                 string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Machine) Reset() {
	*x = Machine{}
	mi := &file_machinedb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Machine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machine) ProtoMessage() {}

func (x *Machine) ProtoReflect() protoreflect.Message {
	mi := &file_machinedb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machine.ProtoReflect.Descriptor instead.
func (*Machine) Descriptor() ([]byte, []int) {
	return file_machinedb_proto_rawDescGZIP(), []int{1}
}

func (x *Machine) GetEndorsementPublicKeyPkix() []byte {
	if x != nil {
		return x.EndorsementPublicKeyPkix
	}
	return nil
}

func (x *Machine) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

var File_machinedb_proto protoreflect.FileDescriptor

const file_machinedb_proto_rawDesc = "" +
	"\n" +
	"\x0fmachinedb.proto\"3\n" +
	"\vMachineList\x12$\n" +
	"\bmachines\x18\x01 \x03(\v2\b.MachineR\bmachines\"e\n" +
	"\aMachine\x12=\n" +
	"\x1bendorsement_public_key_pkix\x18\x01 \x01(\fR\x18endorsementPublicKeyPkix\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeNameB-Z+github.com/ahmedtd/tpm-demo/lib/machinedbpbb\x06proto3"

var (
	file_machinedb_proto_rawDescOnce sync.Once
	file_machinedb_proto_rawDescData []byte
)

func file_machinedb_proto_rawDescGZIP() []byte {
	file_machinedb_proto_rawDescOnce.Do(func() {
		file_machinedb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_machinedb_proto_rawDesc), len(file_machinedb_proto_rawDesc)))
	})
	return file_machinedb_proto_rawDescData
}

var file_machinedb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_machinedb_proto_goTypes = []any{
	(*MachineList)(nil), // 0: MachineList
	(*Machine)(nil),     // 1: Machine
}
var file_machinedb_proto_depIdxs = []int32{
	1, // 0: MachineList.machines:type_name -> Machine
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_machinedb_proto_init() }
func file_machinedb_proto_init() {
	if File_machinedb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_machinedb_proto_rawDesc), len(file_machinedb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_machinedb_proto_goTypes,
		DependencyIndexes: file_machinedb_proto_depIdxs,
		MessageInfos:      file_machinedb_proto_msgTypes,
	}.Build()
	File_machinedb_proto = out.File
	file_machinedb_proto_goTypes = nil
	file_machinedb_proto_depIdxs = nil
}
